# Preparation
set (APP_HEADERS "")
set (APP_SOURCES "")

# Default
set(APP_DEFAULT_HEADERS )
set(APP_DEFAULT_SOURCES "App.cpp")
list(APPEND APP_HEADERS ${APP_DEFAULT_HEADERS})
list(APPEND APP_SOURCES ${APP_DEFAULT_SOURCES})
