# Preparation
set (TEST_HEADERS "")
set (TEST_SOURCES "")

# Default
set(TEST_DEFAULT_HEADERS )
set(TEST_DEFAULT_SOURCES "Test.cpp")
list(APPEND TEST_HEADERS ${TEST_DEFAULT_HEADERS})
list(APPEND TEST_SOURCES ${TEST_DEFAULT_SOURCES})
