# Preparation
set (DEMO_HEADERS "")
set (DEMO_SOURCES "")

# Default
set(DEMO_DEFAULT_HEADERS )
set(DEMO_DEFAULT_SOURCES "Demo.cpp")
list(APPEND DEMO_HEADERS ${DEMO_DEFAULT_HEADERS})
list(APPEND DEMO_SOURCES ${DEMO_DEFAULT_SOURCES})
